sudi: required
services:
  - docker

before_install:
  - docker build -t note5019/docker-react -f Dockerfile.dev .

  #docker run -e CI=true USERNAME/docker-react npm run test
script:
  - docker run -e CI=true note5019/docker-react npm run test