sudo: required
services:
  - docker

befor_install:
  - pwd
  - cd ./complex
  - docker build -t note5019/react-test -f ./client/Dockerfile.dev ./client
script:
  - pwd
  - cd ./client
  - docker run note5019/react-test npm test -- --coverage
after_success:
  - pwd
  - cd ..
  - pwd
  - docker build -t note5019/multi-client ./client
  - docker build -t note5019/multi-nginx ./nginx
  - docker build -t note5019/multi-server ./server
  - docker build -t note5019/multi-worker ./worker
  # Log in to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push Docker image
  - docker push note5019/multi-client
  - docker push note5019/multi-nginx
  - docker push note5019/multi-server
  - docker push note5019/multi-worker